export const techField = [
  { name: "서버/백엔드", option: "server_backend" },
  { name: "웹 프론트엔드", option: "web_frontend" },
  { name: "웹 풀스택", option: "web_fullstack" },
  { name: "안드로이드", option: "android" },
  { name: "iOS", option: "ios" },
  { name: "게임", option: "game" },
  { name: "머신러닝/인공지능", option: "machine_learning_ai" },
  { name: "블록체인", option: "blockchain" },
  { name: "DBA", option: "dba" },
  { name: "개발PM", option: "development_pm" },
  { name: "데브옵스", option: "devops" },
  { name: "디자인", option: "design" },
];
export const techStack = [
  { name: "JavaScript", option: "javascript" },
  { name: "TypeScript", option: "typescript" },
  { name: "React", option: "react" },
  { name: "Vue", option: "vue" },
  { name: "Svelte", option: "svelte" },
  { name: "Nextjs", option: "nextjs" },
  { name: "Nodejs", option: "nodejs" },
  { name: "Java", option: "java" },
  { name: "Spring", option: "spring" },
  { name: "Go", option: "go" },
  { name: "Nestjs", option: "nestjs" },
  { name: "Kotlin", option: "kotlin" },
  { name: "Express", option: "express" },
  { name: "MySQL", option: "mysql" },
  { name: "MongoDB", option: "mongodb" },
  { name: "Python", option: "python" },
  { name: "Django", option: "django" },
  { name: "php", option: "php" },
  { name: "GraphQL", option: "graphql" },
  { name: "Firebase", option: "firebase" },
  { name: "Flutter", option: "flutter" },
  { name: "Swift", option: "swift" },
  { name: "ReactNative", option: "reactnative" },
  { name: "Unity", option: "unity" },
  { name: "AWS", option: "aws" },
  { name: "Kubernetes", option: "kubernetes" },
  { name: "Docker", option: "docker" },
  { name: "Git", option: "git" },
  { name: "Figma", option: "figma" },
  { name: "Zeplin", option: "zeplin" },
  { name: "Jest", option: "jest" },
];
